name: Doc

on:
  release:
    types: [published, edited, prereleased]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Crystal
      uses: oprypin/install-crystal@v1
      with:
        crystal: nightly
    - name: Build documentation
      run: crystal docs
    - name: Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
