name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Prerequisites
      run: gem install rake
    - name: BuildShard
      run: rake build_shard
    - name: TestScript
      run: crystal test.cr
