name: WinTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '45 03 * * 6'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-ruby@v1
    - uses: microsoft/setup-msbuild@v1.1
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
     
    - name: Download source
      uses: actions/checkout@v2
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: nightly
    - name: Build shard
      run: rake build_shard
    - name: Test directories
      run: dir build/mruby/lib
    - name: Test script
      run: crystal build test.cr
    - name: Run script
      run: ./test
